"""Compatibility exports for shared constants."""

from auth.views import (
    LEADERBOARD_SECTION_META,
    RESULT_MODAL_TYPE_CONFIG,
    RU_WEEKDAY,
    RU_WEEKDAY_SHORT,
    TRAINING_BLOCK_LABELS,
    TRAINING_DIRECTION_LABELS,
    TRAINING_RESULT_TYPE_LABELS,
)

__all__ = [
    "LEADERBOARD_SECTION_META",
    "RESULT_MODAL_TYPE_CONFIG",
    "RU_WEEKDAY",
    "RU_WEEKDAY_SHORT",
    "TRAINING_BLOCK_LABELS",
    "TRAINING_DIRECTION_LABELS",
    "TRAINING_RESULT_TYPE_LABELS",
]

