# Generated by Django 6.0.3 on 2026-04-07 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('section', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('metabolic', 'Metabolic')], max_length=16)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('rx', 'RX'), ('scaled', 'SCALED')], default='rx', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-training_date', '-updated_at'],
                'unique_together': {('user', 'training_date', 'section')},
            },
        ),
    ]
