# Generated by Django 6.0.4 on 2026-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_auth", "0007_seed_default_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weekly_goal",
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]

