# Generated by Django 6.0.4 on 2026-04-10 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0008_userprofile_weekly_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('direction', models.CharField(choices=[('fbb', 'FBB'), ('crossfit', 'Crossfit with Denis Zalozniy'), ('gymnastics', 'Gymnastics'), ('workout', 'Workout of the day')], default='fbb', max_length=32)),
                ('visibility', models.CharField(choices=[('coaches', 'Only for coaches'), ('all', 'For all')], default='all', max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('pink', 'Pink'), ('violet', 'Violet')], default='blue', max_length=16)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('ready', 'Ready complex')], default='manual', max_length=16)),
                ('ready_workout_type', models.CharField(blank=True, default='', max_length=32)),
                ('ready_complex_type', models.CharField(blank=True, default='', max_length=32)),
                ('ready_complex_name', models.CharField(blank=True, default='', max_length=255)),
                ('ready_plan_title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_trainings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-training_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('gymnastics', 'Gymnastics'), ('custom', 'Custom')], default='strength', max_length=16)),
                ('block_custom_name', models.CharField(blank=True, default='', max_length=255)),
                ('exercise_name', models.CharField(max_length=255)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('time', 'Time'), ('weight', 'Weight'), ('reps', 'Reps count')], default='time', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='mini_auth.admintraining')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
