# Generated by Django 6.0.4 on 2026-04-16 05:36

from django.db import migrations, models


def backfill_exercise_kind(apps, schema_editor):
    admin_training_exercise = apps.get_model('mini_auth', 'AdminTrainingExercise')
    admin_training_exercise.objects.filter(exercise_name__iexact='Benchmarks').update(exercise_kind='benchmarks')
    admin_training_exercise.objects.exclude(exercise_name__iexact='Benchmarks').update(exercise_kind='exercise')


def reverse_backfill_exercise_kind(apps, schema_editor):
    admin_training_exercise = apps.get_model('mini_auth', 'AdminTrainingExercise')
    admin_training_exercise.objects.update(exercise_kind='exercise')


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0014_userprofile_role_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintrainingexercise',
            name='exercise_kind',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('benchmarks', 'Benchmarks')], default='exercise', max_length=16),
        ),
        migrations.RunPython(backfill_exercise_kind, reverse_backfill_exercise_kind),
    ]
