# Generated by Django 6.0.4 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0015_admintrainingexercise_exercise_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintraining',
            name='direction',
            field=models.CharField(
                choices=[
                    ('fbb', 'FBB'),
                    ('crossfit', 'Crossfit with Denis Zalozniy'),
                    ('gymnastics', 'Gymnastics'),
                    ('workout', 'Training of the day'),
                    ('functional', 'Functional training'),
                    ('strength', 'Strength training'),
                ],
                default='fbb',
                max_length=32,
            ),
        ),
    ]
