# Generated by Django 6.0.4 on 2026-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0016_alter_admintraining_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlibraryitem',
            name='movement_group',
            field=models.CharField(blank=True, choices=[('squat', 'Squat'), ('push', 'Push'), ('pull', 'Pull'), ('bend', 'Bend')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='comment_for_athletes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='comment_for_coaches',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='manual_description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='manual_description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='manual_result_type',
            field=models.CharField(blank=True, choices=[('time', 'Time'), ('weight', 'Weight'), ('reps', 'Reps count')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='admintraining',
            name='manual_sets',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admintraining',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('library', 'Library'), ('ready', 'Ready complex')], default='manual', max_length=16),
        ),
    ]
