# Generated by Django 6.0.4 on 2026-04-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0018_alter_adminlibraryitem_benchmark_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintrainingexercise',
            name='library_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_exercises', to='mini_auth.adminlibraryitem'),
        ),
    ]
