# Generated by Django 6.0.4 on 2026-04-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0019_admintrainingexercise_library_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='mini_auth.admintraining'),
        ),
        migrations.AddConstraint(
            model_name='trainingresult',
            constraint=models.UniqueConstraint(condition=models.Q(('training__isnull', False)), fields=('user', 'training', 'section'), name='uniq_training_result_user_training_section'),
        ),
        migrations.AddConstraint(
            model_name='trainingresult',
            constraint=models.UniqueConstraint(condition=models.Q(('training__isnull', True)), fields=('user', 'training_date', 'section'), name='uniq_training_result_user_date_section_legacy'),
        ),
    ]
