# Generated by Django 6.0.4 on 2026-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_auth', '0022_userbenchmarkresultprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
